config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :validate_email
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_many :addresses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    respond_to do |format|
      format.html { render locals: { users: User.all } }
    end
  end

  def new
    respond_to do |format|
      format.html { render locals: { user: User.new } }
    end
  end

  def create
    user = User.create(user_params)
    if user.errors.any?
      respond_to do |format|
        format.html { render 'new', locals: { user: user } }
      end
    else
      redirect_to action: :index
    end
  end

  def validate_email
    users = User.where(username: params[:email])
    respond_to do |format|
      format.json { render json: valid = (users.size == 0) }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :age, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<h1>Hello users!</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for user, html: { 'data-validate-email-url' => validate_email_users_path } do |f| %>
  <div class="form-group">
    <%= f.label :username %>:
    <%= f.text_field :username, class: 'form-control js-username' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>:
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name %>:
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :age %>:
    <%= f.number_field :age, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary js-new-user-button' %>
<% end %>